### PR TITLE
Assignment3

### PR DESCRIPTION
**Pull request by gooty12**
Clean termination.

### CODE REVIEW

**Comment by regehr** [comment]
github won't merge this until you fix conflicts

**Comment by gooty12** [comment]
Sorry...I totally forgot this thing. I have verified my changes again.....these are just minor changes. It shouldn't take more than a couple of minutes to resolve. Shall we resolve these after class?  Attaching a screenshot of _git diff_
merge_conflicts

**Comment by regehr** [comment]
you can resolve this yourself, then prepare a new pull request

**Comment by gooty12** [comment]
ohh...okay. You mean modify my pipe.c such that it doesn't create any conflict and then create a pull request?  To do it in any other way I don't have write permissions to this repo.

**Comment by regehr** [comment]
you've made a mistake with git, not with pipe.c

**Comment by regehr** [comment]
you need to issue a pull request that I can merge

**Comment by regehr** [comment]
googling something like this will give you some info:
github pull request fix conflicts

**Comment by gooty12** [comment]
Sure prof...will do. Thanks. I better learn more about git :(

**Pull request closed without merging**
